spring:
  datasource:
    url: jdbc:postgresql://db:5432/jira
    username: ${database.username}
    password: ${database.password}
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: ${mail.username}
    password: ${mail.password}
    port: 587
